### ISSUE TITLE
Handle connection drops

### ISSUE THREAD

**Issue by bascht** [creditkarma/good-influx#1]
The adapter needs to handle drops / resets gracefully. If we're running in a Docker context it would be okay to give a Warning on `STDERR`.

**Comment by AlecHFerguson** [comment]
@bascht: Have you tried setting `errorThreshold` in your configs?  I believe this should work:

```javascript
const options = {
    ops: {
        interval: 1000
    },
    reporters: {
        influx: [{
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{ ops: '*' }]
        }, {
            module: 'good-influx',
            args: ['http://localhost:8086/write?db=good', {
                threshold: 10,
                errorThreshold: 5  // <= Set error threshold here
            }]
        }]
    }
};

server.register({
    register: require('good'),
    options: options
   ...
```

This will retry up to `errorThreshold` times before it fails.  It works well when your HTTP endpoint is down for short periods.  I tested locally, turning off my Telegraf collector temporarily; and when I turned it back on I was able to capture all events with no loss.

Another solution is to use UDP, rather than HTTP.  UDP is connectionless, so it doesn't care if the packet gets received; once your Influx collector comes back up the data will be captured.  The disadvantage is that data can be lost without you knowing it.

We have a pull request to add UDP support to this module; you can check it out here:
https://github.com/fhemberger/good-influx/pull/3

As mentioned there, we have published a scoped module that you can try.  Feel free to give it a whirl and to add any feedback you have in the PR.

**Comment by bascht** [comment]
@AlecHFerguson Thanks for your input and your contribution in #3! I'm currently busy in other projects but I'll take it for a spin once I find some time! :smiley:

**Comment by AlecHFerguson** [comment]
Closing for now since I think this has been resolved.  Feel free to reopen if you see this again and the solutions outlined above do not allow you to address the issue.
