### ISSUE TITLE
upgrade good-udp

### ISSUE THREAD

**Issue by pi0** [creditkarma/good-influx#19]
Warning during npm install:

good-influx > good-udp > fast-safe-stringify@1.0.9: use 1.1.0+ see https://github.com/davidmarkclements/fast-safe-stringify/issues/4

**Comment by AlecHFerguson** [comment]
Thanks for reporting this @pi0 .  Can you file a ticket with the Good UDP project? It looks like their master branch specifies a 1.1.0+ version, but they just haven't released it yet.
https://github.com/hapijs/good-udp/compare/v4.0.0...master

We generally would not address issues like this in projects we require, per se, since it's the responsibility of the project owner. In using Good Influx, have you encountered the scenario described in https://github.com/davidmarkclements/fast-safe-stringify/issues/4? Application crashes due to objects being modified rather than copied?

**Comment by fhemberger** [comment]
Ref: https://github.com/hapijs/good-udp/issues/46

**Comment by fhemberger** [comment]
Fixed, published `good-influx@2.3.2`.

**Comment by pi0** [comment]
@fhemberger Wow. Thank you so much ❤️
